import Head from "next/head";

export default function Main({ children }) {
    return (
        <>
            <Head>
                <title>arica</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav>Navbar</nav>
            {children}
            <footer>Footer</footer>
        </>
    );
}
